[package]
name = "cubus"
authors = ["Ulrich Singer <bit.fu@gmx.net>"]
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
